// <auto-generated />
using System;
using FollowUP.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FollowUP.Infrastructure.Migrations
{
    [DbContext(typeof(FollowUPContext))]
    [Migration("20201002172549_AddScheduleRelations")]
    partial class AddScheduleRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FollowUP.Core.Domain.AccountProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<Guid>("ProxyId");

                    b.HasKey("Id");

                    b.ToTable("AccountProxies");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.AccountSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<int>("ActionsPerDay");

                    b.Property<int>("FollowsPerDay");

                    b.Property<int>("LikesPerDay");

                    b.Property<int>("MaxIntervalMilliseconds");

                    b.Property<int>("MinIntervalMilliseconds");

                    b.Property<int>("UnfollowsPerDay");

                    b.HasKey("Id");

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.AccountStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<int>("ActionsCount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("FollowsCount");

                    b.Property<int>("LikesCount");

                    b.Property<int>("UnfollowsCount");

                    b.HasKey("Id");

                    b.ToTable("AccountStatistics");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.ChildComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("AuthorPk")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("LikesCount");

                    b.Property<Guid>("ParentCommentId");

                    b.Property<string>("ProfilePictureUri")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ChildComments");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("AuthorPk")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("LikesCount");

                    b.Property<string>("ParentImageUri")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("ParentMediaId")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("ProfilePictureUri")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.DailyPromotionPercentage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Percentage");

                    b.Property<Guid>("PromotionId");

                    b.Property<Guid>("SingleScheduleDayId");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SingleScheduleDayId");

                    b.ToTable("DailyPromotionPercentages");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.DayGroupConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Order");

                    b.Property<Guid>("ScheduleGroupId");

                    b.Property<Guid>("SingleScheduleDayId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.HasIndex("SingleScheduleDayId");

                    b.ToTable("DayGroupConnections");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.ExplicitDaySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("SingleScheduleDayId");

                    b.HasKey("Id");

                    b.HasIndex("SingleScheduleDayId");

                    b.ToTable("ExplicitDaySchedules");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.FollowedProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ProfilePk")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("FollowedProfiles");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.InstagramAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActionCooldown");

                    b.Property<string>("AndroidDevice")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("AuthenticationStep");

                    b.Property<DateTime>("BannedUntil");

                    b.Property<DateTime>("CommentsModuleExpiry");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15);

                    b.Property<string>("Pk")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("PreviousCooldownMilliseconds");

                    b.Property<DateTime>("PromotionsModuleExpiry");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("InstagramAccounts");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.InstagramProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<bool>("IsTaken");

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Username")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("InstagramProxies");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.MonthlyGroupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<Guid>("ScheduleGroupId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleGroupId");

                    b.ToTable("MonthlyGroupSchedules");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastMediaId")
                        .HasMaxLength(100);

                    b.Property<string>("NextMinId")
                        .HasMaxLength(100);

                    b.Property<DateTime>("NextMinIdDate");

                    b.Property<int>("PromotionType");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.PromotionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("Id");

                    b.ToTable("PromotionComments");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.ScheduleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<int>("Colour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("ScheduleGroups");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.SingleScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("SingleScheduleDays");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320);

                    b.Property<string>("FullName")
                        .HasMaxLength(60);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<bool>("Verified");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FollowUP.Core.Domain.DailyPromotionPercentage", b =>
                {
                    b.HasOne("FollowUP.Core.Domain.Promotion", "Promotion")
                        .WithMany("DailyPromotionPercentages")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FollowUP.Core.Domain.SingleScheduleDay")
                        .WithMany("DailyPromotionPercentages")
                        .HasForeignKey("SingleScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FollowUP.Core.Domain.DayGroupConnection", b =>
                {
                    b.HasOne("FollowUP.Core.Domain.ScheduleGroup", "ScheduleGroup")
                        .WithMany()
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FollowUP.Core.Domain.SingleScheduleDay", "SingleScheduleDay")
                        .WithMany("DayGroupConnections")
                        .HasForeignKey("SingleScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FollowUP.Core.Domain.ExplicitDaySchedule", b =>
                {
                    b.HasOne("FollowUP.Core.Domain.SingleScheduleDay", "SingleScheduleDay")
                        .WithMany("ExplicitDaySchedules")
                        .HasForeignKey("SingleScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FollowUP.Core.Domain.MonthlyGroupSchedule", b =>
                {
                    b.HasOne("FollowUP.Core.Domain.ScheduleGroup", "ScheduleGroup")
                        .WithMany()
                        .HasForeignKey("ScheduleGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
